#
# Licensed under the GPL License. You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
#
# THIS PACKAGE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,
# WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR
# PURPOSE.
#

version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.sun.mail:jakarta.mail
    versions:
    - ">= 2.0.0"
  - dependency-name: jakarta.el:jakarta.el-api
    versions:
    - ">= 4.0.0"
  - dependency-name: jakarta.inject:jakarta.inject-api
    versions:
    - ">= 2.0.0"
  - dependency-name: jakarta.transaction:jakarta.transaction-api
    versions:
    - ">= 2.0.0"
  - dependency-name: net.trajano.wagon:wagon-git
    versions:
    - "< 2.0.5"
    - ">= 2.0.4.a"
  - dependency-name: org.apache.tomcat:tomcat-catalina
    versions:
    - ">= 10.0.0"
  - dependency-name: org.apache.tomcat:tomcat-coyote
    versions:
    - ">= 10.0.0"
  - dependency-name: org.apache.tomcat:tomcat-dbcp
    versions:
    - ">= 10.0.0"
  - dependency-name: org.apache.tomcat:tomcat-dbcp
    versions:
    - ">= 10.0.0"
  - dependency-name: org.apache.tomcat:tomcat-jasper
    versions:
    - ">= 10.0.0"
  - dependency-name: org.eclipse.jetty:jetty-jspc-maven-plugin
    version:
    - ">= 10.0.0"
